 version: 2
 updates:
   - package-ecosystem: "npm"
     directory: "/"
     schedule:
       interval: "never"
   - package-ecosystem: "maven"
     directory: "/"
     schedule:
       interval: "never"