apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: crud-api
  name: crud-api
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IubGFiLmludCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJIYXJib3IxMjM0NSIsImF1dGgiOiJZV1J0YVc0NlNHRnlZbTl5TVRJek5EVT0ifX19
kind: Secret
metadata:
  name: harbor-registry
  namespace: crud-api
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6RENDQXJTZ0F3SUJBZ0lVUGgzN1FlclJLTW1oeFRCSi9ubGwzbmVMRXZnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BERVpNQmNHQTFVRUF3d1FZM0oxWkMxaGNHa3ViR0ZpTG1sdWRERUxNQWtHQTFVRUJoTUNRbEl4RWpBUQpCZ05WQkFjTUNWTmhieUJRWVhWc2J6QWVGdzB5TWpFeE1qVXhPRFE1TlRWYUZ3MHlNekV4TWpVeE9EUTVOVFZhCk1JR0tNUXN3Q1FZRFZRUUdFd0pDVWpFU01CQUdBMVVFQ0F3SlUyRnZJRkJoZFd4dk1SMHdHd1lEVlFRSERCUlQKWVc4Z1FtVnlibUZrYnlCa2J5QkRZVzF3YnpFVU1CSUdBMVVFQ2d3TFRHRmliM0poZEc5eWFXOHhGekFWQmdOVgpCQXNNRGt4aFltOXlZWFJwYjI0Z1JHVjJNUmt3RndZRFZRUUREQkJqY25Wa0xXRndhUzVzWVdJdWFXNTBNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5V09oeG5nWGxwRGhjOC96NnNIcnZBS28KcmpWamZvbHFrWkMzZE1tYlBmem5CNEhBRXI3MkhDbHpOM1lOMGhraEd1WW52ejR5bzBSOVVYc1NKaUgrUER4VQpKL1pJZE5ObUlmKzJEeEVTaEhWYXNVUkxhMGdOaC9VRmRmSUlyRmhiS3lETVFzMTd2NWNjZ2s0Ni9tME4zRzI1ClAzckhVNFNSZnErU3J6NGgwVEtwM0w1YldtQlllb1d0L3orMEJIZzM0N1hXS1NEdDNVUCtnWU9XM09HVHIzYm8KWHc0OGVMbHl2SXE1RDA2amRpdnc2b2FoQjh4QitZb2xQSTc3RmZ2SmxxMk4rdUJ4cHdmOEpycXpYMGY5cm5Gbwo2bEtWbnhNVjRpQ2xXeloxcTlpR2JnbkxSKzJCSEM4NlZLTTlrTGVIelJCYVd3YnpLTjhTMngrRXM2Mzd2d0lECkFRQUJvM2N3ZFRBZkJnTlZIU01FR0RBV2dCUXVZUWI5R0Rud2FPa0VDYWIrVkRzT0ZXTmZvekFKQmdOVkhSTUUKQWpBQU1Bc0dBMVVkRHdRRUF3SUU4REFiQmdOVkhSRUVGREFTZ2hCamNuVmtMV0Z3YVM1c1lXSXVhVzUwTUIwRwpBMVVkRGdRV0JCVG1PcDNBaWR2L1Q5dU9yWlpESmgxN0hiM0MrVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCkFXeXBmcXpPZEl1S1B5Um13TTA0Y2NicmRtd0tpbFFDZWRRQUhId24vaFBmU29kSHRRc2lySjM2R1Uyc01RV28KTm95dnp1UmZlY1FPcWF0VVNQTFd5NmVTaVdwMC9XN2E3UlVLVVB2OEhBZThPTHJrT1IzLzl4VlVsRHZReUFWZwpnK2RQMHQ2VnlLT1cvR1ZTcm9hQ2xqcnNtWm4yaUQ5VFVUTE0xdldnK0s5VHZaWE8zNUZjdnJuU1lLV1lobHg0CjVsNHZ5bHB1MHhTVWtTSDZZTG5sL1puOTBudTlBNWVWRDdpOWh4WEw0cnF0cDcydUdHNlhkYUZrSWpaWEVDUDIKalV4MGQrSG1IK1lZRSt5bjUxbkVqQitLMUNoOWc4ZVlhL2FRMjc3OUs2VWI0bE9BOHNoRjdvM3lRUGlsU1dXMwowZVJzNGt1QWhJL0J1Yno5Mmh3ZHNRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRREpZNkhHZUJlV2tPRnoKei9QcXdldThBcWl1TldOK2lXcVJrTGQweVpzOS9PY0hnY0FTdnZZY0tYTTNkZzNTR1NFYTVpZS9QaktqUkgxUgpleEltSWY0OFBGUW45a2gwMDJZaC83WVBFUktFZFZxeFJFdHJTQTJIOVFWMThnaXNXRnNySU14Q3pYdS9seHlDClRqcitiUTNjYmJrL2VzZFRoSkYrcjVLdlBpSFJNcW5jdmx0YVlGaDZoYTMvUDdRRWVEZmp0ZFlwSU8zZFEvNkIKZzViYzRaT3ZkdWhmRGp4NHVYSzhpcmtQVHFOMksvRHFocUVIekVINWlpVThqdnNWKzhtV3JZMzY0SEduQi93bQp1ck5mUi8ydWNXanFVcFdmRXhYaUlLVmJObldyMkladUNjdEg3WUVjTHpwVW96MlF0NGZORUZwYkJ2TW8zeExiCkg0U3pyZnUvQWdNQkFBRUNnZ0VBUUt6dGpHYU85THpNbXJ2akVyWjZkV1BKTmtGUkZaY2VFV2VQYzBNM3h2Mk0KV0gzVDZIRkphcHZwTTV1SExyMEJRN2s4ZEkrT0JaNytQQWV4T1d2YlVRN3kyKzZkTUYrZndqVjBDM3lwSEw3dgpoRlJ4Z0IrZ3NOUUFqL05OMDhPQWErWlprdTZZMmx1MlBTYlFqVnNLZzRyOVhpU1pGUHBURzROWk1VeGI0ZW00ClBCb1hkeVBZeUFiMkkvNHRtWHBsMmpYU2EzcWVzSDFtODFIWTZxMURYTGIzSm5LSXhaV1FVSXlPVndxVzdCWlMKQ1JkdXk0NlJiYzY5aTlYbU11VmpZTU1zdmxjR0s3NkVxZmdHcUV4cHNNZFZ2bjFGNHpvMXBQa05wT3BCVUFWcApLL2RPUC9VSFMvSnRKS1JnSEhMaDlHQkY0UnZJR3pHOHphVVRGK3dYVVFLQmdRRHlQTWxsekZBR1F3dXZ2a3lPCkxMTEdNRXd3VG85VytxMGdFWjRnaHJDa2VIb3ZkeExzbFBndXpSRW1IMWZIL1NhYnRIK094T3l1TWNMRjA0bDcKWGFTbXFBVXB5MFV6YnlBUGw0eU40Q0dKSFpnNFlmR0xmS2VzMmdEREVDTURoU0o3aE45ZTFkUGlLSzhMSUpUNQpQS2hCR3hGbW1mZ1pnOFBYTTAzQ3dnMWNCd0tCZ1FEVTFMcXd1R05aTmt6QmlRbWJMSDBGSmdmdXl3eEVFNHVaCnNack5JN01GRytJcjZyamw1Y3RXZUl0UE1XUXJQa2dTTmZrb2IxbVdTQXpuM043OVdEczdDYm41SjcxWHRBWUoKQ2lxc0habWQvZFN4NmxkNWhQb3NCTVZyR0FEeFhRTGdJK1Z4ZENvWldhem9WdUtPSC8wbDQwcHlSWXRXcGFHYwoyUEsvWFlOa2lRS0JnQVV4Y212aFJuSHI3QXMzZkRLc0dLVVJFZ0VUSGhXU1NEWGd5dEFOc3luRGYzTVhEV3ZQCkFjY1hGR0FKMmZycW5YSkhHMWozTmMvQ04xZkFZamtuMThqTzMxVjNDeVBBSlNMUWIrMzJ1U0ZVWmhnSFdZTlIKQjlNMzFUNVpVVGJaR3RVbEV4allZck45aGNzcVJxZFZPcEl5djF2QXYwWGt3a1VSejMvMll3enZBb0dCQUtkOQpUZm82OFh4SW5qa0VWam4yMWVCU1lKWE0xemRQeG1IS2drK0VFNk1tb1dQOFVVd2kvbFZyZ2Y1dG1TM3EwcDc2Ck9MMVllOEVuckhoZnVtRFhxYTA1WjFDcnRIY3Jwa0JBN3ZvS1JWVXZaODRuNUhVdWNBNXFKczZ6MGpJZ0IxNUwKQVlxNloxTVIzbC90MkZjTzE1S1VmNGJVTWVhYmJFYlorSmNleVlNNUFvR0JBTnlrcno0RW1Xdm44Ukp3enY1Zgp6QVFTenF3SG1DeVNQb3orUEhsTEx0NkVUOGRvd09VT1J0dkJnQzFlRDBBWWhEV1V2K3Y5TG9KTUpYeVh3cVU2CnlFQW1RK2J4YkI3a3FWVjNiQW5lMm1EMHozZUdmV3JGTnRpNGQrWkt0eUVmWFhHYlQxeEQrL0N4SkdBNW1JY3kKc2hrM05HNStGZTEraTVsYUZMeVNjdlpsCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: crud-api-tls
  namespace: crud-api
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: crud-database-creds
  namespace: crud-api
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql.database.svc.cluster.local:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "36FMYk3CMU"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-api-deployment
  namespace: crud-api
  labels:
    app: crud-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-api-app
  template:
    metadata:
      labels:
        app: crud-api-app
    spec:
      containers:
        - name: crud-api
          image: harbor.lab.int/crud-users/crud-users-api:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 10
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: crud-database-creds
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: crud-database-creds
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-database-creds
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                secretKeyRef:
                  name: crud-database-creds
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
      imagePullSecrets:
      - name: harbor-registry            
---
apiVersion: v1
kind: Service
metadata:
  name: crud-api-service
  namespace: crud-api
spec:
  selector:
    app: crud-api-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-api-ingress
  namespace: crud-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "crud-api.lab.int"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crud-api-service
                port:
                  number: 8080
  ingressClassName: nginx
  tls:
  - hosts:
    - crud-api.lab.int
    secretName: crud-api-tls
---
apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    name: crud-api-deployment
    namespace: crud-api
  spec:
    maxReplicas: 10
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: crud-api-deployment
kind: List
